using System;
using System.Numerics;
using System.Security.Cryptography;

namespace TelemetryDashboard.Core.Security;

/// <summary>
/// RFC 8032 Ed25519 (PureEdDSA over Curve25519 with SHA-512).
/// </summary>
/// <remarks>
/// Verification consumes the public key <em>only</em>. The previous implementation fell back to
/// treating the supplied public key as a private seed and re-deriving a signature from it, which
/// let anyone holding the public key mint valid signatures — defeating the zero-trust packet
/// authentication this module exists to provide.
/// <para>
/// This is a managed BigInteger implementation: it is constant-shape but not constant-time, so it
/// suits telemetry packet authentication rather than defending a key against a local side-channel
/// attacker.
/// </para>
/// </remarks>
public static class Ed25519
{
    /// <summary>Length in bytes of a private key seed.</summary>
    public const int SeedSize = 32;

    /// <summary>Length in bytes of an encoded public key.</summary>
    public const int PublicKeySize = 32;

    /// <summary>Length in bytes of a signature.</summary>
    public const int SignatureSize = 64;

    /// <summary>
    /// Order of the prime-order subgroup generated by B: L = 2²⁵² + 27742317777372353535851937790883648493.
    /// </summary>
    /// <remarks>
    /// Derived from its definition rather than pasted as a 76-digit literal. The literal previously
    /// used here was wrong from the 28th digit on, so <c>[L]B</c> was not the identity and the
    /// verification equation could never balance for a genuine signature — which is what the
    /// signature-forgery fallback was built to paper over.
    /// </remarks>
    private static readonly BigInteger L =
        (BigInteger.One << 252) + BigInteger.Parse("27742317777372353535851937790883648493");

    /// <summary>Generates a fresh random seed and its matching public key.</summary>
    public static (byte[] PrivateKey, byte[] PublicKey) GenerateKeyPair()
    {
        byte[] seed = RandomNumberGenerator.GetBytes(SeedSize);
        return (seed, DerivePublicKey(seed));
    }

    /// <summary>Derives the public key for a 32-byte private seed.</summary>
    public static byte[] DerivePublicKey(byte[] privateSeed)
    {
        BigInteger scalar = ClampScalar(privateSeed, out _);
        return Ed25519Point.Base.Multiply(scalar).Encode();
    }

    /// <summary>Produces a 64-byte signature over <paramref name="message"/>.</summary>
    /// <param name="privateSeed">32-byte private seed.</param>
    public static byte[] Sign(byte[] message, byte[] privateSeed)
    {
        message ??= Array.Empty<byte>();
        BigInteger a = ClampScalar(privateSeed, out byte[] prefix);
        byte[] publicKey = Ed25519Point.Base.Multiply(a).Encode();

        // r = SHA-512(prefix || M) mod L
        BigInteger r = ReduceModL(SHA512.HashData(Concat(prefix, message)));
        byte[] encodedR = Ed25519Point.Base.Multiply(r).Encode();

        // k = SHA-512(R || A || M) mod L
        BigInteger k = ReduceModL(SHA512.HashData(Concat(encodedR, publicKey, message)));
        BigInteger s = (r + k * a) % L;

        var signature = new byte[SignatureSize];
        Buffer.BlockCopy(encodedR, 0, signature, 0, 32);
        Buffer.BlockCopy(Ed25519Point.EncodeLittleEndian(s), 0, signature, 32, 32);
        return signature;
    }

    /// <summary>
    /// Verifies a signature using only the public key. Returns false for any malformed input,
    /// non-canonical scalar, off-curve point, or equation mismatch.
    /// </summary>
    public static bool Verify(byte[] message, byte[] signature, byte[] publicKey)
    {
        if (signature is not { Length: SignatureSize }) return false;
        if (publicKey is not { Length: PublicKeySize }) return false;
        message ??= Array.Empty<byte>();

        try
        {
            byte[] encodedR = signature[..32];
            BigInteger s = Ed25519Point.DecodeLittleEndian(signature[32..]);
            if (s >= L) return false; // non-canonical S permits signature malleability

            Ed25519Point? r = Ed25519Point.Decode(encodedR);
            Ed25519Point? a = Ed25519Point.Decode(publicKey);
            if (r is null || a is null) return false;

            BigInteger k = ReduceModL(SHA512.HashData(Concat(encodedR, publicKey, message)));

            // Accept only when [S]B == R + [k]A.
            byte[] left = Ed25519Point.Base.Multiply(s).Encode();
            byte[] right = r.Value.Add(a.Value.Multiply(k)).Encode();

            return CryptographicOperations.FixedTimeEquals(left, right);
        }
        catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or FormatException)
        {
            return false;
        }
    }

    /// <summary>
    /// Expands a seed into the clamped scalar and the nonce prefix, per RFC 8032 section 5.1.5.
    /// </summary>
    private static BigInteger ClampScalar(byte[] privateSeed, out byte[] prefix)
    {
        if (privateSeed is not { Length: SeedSize })
        {
            throw new ArgumentException($"Ed25519 private seed must be exactly {SeedSize} bytes.", nameof(privateSeed));
        }

        byte[] hash = SHA512.HashData(privateSeed);

        var scalarBytes = new byte[32];
        Buffer.BlockCopy(hash, 0, scalarBytes, 0, 32);
        scalarBytes[0] &= 248;  // clear the three lowest bits (cofactor)
        scalarBytes[31] &= 127; // clear the highest bit
        scalarBytes[31] |= 64;  // set the second-highest bit

        prefix = new byte[32];
        Buffer.BlockCopy(hash, 32, prefix, 0, 32);

        return Ed25519Point.DecodeLittleEndian(scalarBytes);
    }

    private static BigInteger ReduceModL(byte[] hash) => Ed25519Point.DecodeLittleEndian(hash) % L;

    private static byte[] Concat(params byte[][] parts)
    {
        int total = 0;
        foreach (byte[] part in parts) total += part.Length;

        var buffer = new byte[total];
        int offset = 0;
        foreach (byte[] part in parts)
        {
            Buffer.BlockCopy(part, 0, buffer, offset, part.Length);
            offset += part.Length;
        }
        return buffer;
    }
}
