using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using TelemetryDashboard.Core.Interfaces;
using TelemetryDashboard.Core.Models;
using TelemetryDashboard.Core.Services;
using TelemetryDashboard.Core.Analytics;

namespace TelemetryDashboard.Infrastructure.Integrations;

/// <summary>
/// Multi-Channel Alert Forwarder.
/// Dispatches anomaly alerts, waveform snapshots (ASCII & SVG), and AI summaries
/// to Slack (Block Kit), Discord (Embeds), Telegram Bot API, and generic HTTP Webhooks with throttling.
/// </summary>
public class MultiChannelAlertForwarder : IMultiChannelAlertForwarder
{
    private readonly HttpClient _httpClient;
    private readonly ConcurrentDictionary<string, (DateTime LastAlertTime, double LastZScore)> _channelThrottles = new(StringComparer.OrdinalIgnoreCase);
    private readonly Func<DateTime> _utcNow;

    public AlertChannelConfig Config { get; set; }

    /// <param name="utcNow">
    /// Clock used to stamp dispatches. Injectable so throttling is deterministic under test:
    /// the dispatch path previously read <see cref="DateTime.UtcNow"/> directly while callers
    /// drove a simulated timeline, so the two clocks only agreed on the day the code was written.
    /// </param>
    public MultiChannelAlertForwarder(
        HttpClient? httpClient = null,
        AlertChannelConfig? config = null,
        Func<DateTime>? utcNow = null)
    {
        _httpClient = httpClient ?? new HttpClient();
        Config = config ?? new AlertChannelConfig();
        _utcNow = utcNow ?? (() => DateTime.UtcNow);
    }

    public void RecordAlert(string channelName, double zScore, DateTime timestamp)
    {
        _channelThrottles[channelName] = (timestamp, zScore);
    }

    public bool ShouldThrottle(string channelName, double zScore, DateTime timestamp)
    {
        if (Config.ThrottleCooldownSec <= 0) return false;

        if (_channelThrottles.TryGetValue(channelName, out var info))
        {
            double elapsed = (timestamp - info.LastAlertTime).TotalSeconds;
            double zDiff = Math.Abs(zScore - info.LastZScore);

            // Compare on magnitude: a clock skew or an out-of-order timestamp produced a negative
            // elapsed, which satisfied "< cooldown" and silently suppressed alerts indefinitely.
            if (Math.Abs(elapsed) < Config.ThrottleCooldownSec && zDiff < Config.MinZScoreJumpForBypass)
            {
                return true;
            }
        }
        else
        {
            _channelThrottles[channelName] = (timestamp, zScore);
        }

        return false;
    }

    public void ResetThrottling()
    {
        _channelThrottles.Clear();
    }

    public string FormatSlackPayload(AnomalyResult anomaly, string aiDiagnosis, string sparkline)
    {
        var blocks = new List<object>
        {
            new
            {
                type = "header",
                text = new { type = "plain_text", text = $"🚨 [CRITICAL ALERT] {anomaly.ChannelName} Anomaly", emoji = true }
            },
            new
            {
                type = "section",
                text = new { type = "mrkdwn", text = $"*AI Diagnosis:*\n{(string.IsNullOrWhiteSpace(aiDiagnosis) ? "Anomaly detected" : aiDiagnosis)}\n*Waveform Snapshot:*\n`{sparkline}`" }
            },
            new
            {
                type = "section",
                fields = new object[]
                {
                    new { type = "mrkdwn", text = $"*Node / Channel:*\n{anomaly.ChannelName}" },
                    new { type = "mrkdwn", text = $"*Z-Score:*\n{anomaly.ZScore:F2}σ" },
                    new { type = "mrkdwn", text = $"*Current Value:*\n{anomaly.CurrentValue:F2}" },
                    new { type = "mrkdwn", text = $"*Est. Breach Time:*\n{(anomaly.EstimatedTimeToBreachSec > 0 ? $"{anomaly.EstimatedTimeToBreachSec:F1}s" : "N/A")}" }
                }
            },
            new
            {
                type = "context",
                elements = new object[]
                {
                    new { type = "mrkdwn", text = $"Generated by TelemetryDashboard AI Hub • {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}Z" }
                }
            }
        };

        var options = new JsonSerializerOptions
        {
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            WriteIndented = false
        };
        return JsonSerializer.Serialize(new { blocks }, options);
    }

    public string FormatDiscordPayload(AnomalyResult anomaly, string aiDiagnosis, string sparkline)
    {
        int color = anomaly.ZScore >= 3.0 ? 16723555 : 16753920; // 0xFF2E63 (Red) or 0xFFA500 (Orange)
        string description = string.IsNullOrWhiteSpace(aiDiagnosis) ? "Anomaly detected" : aiDiagnosis;
        if (!string.IsNullOrWhiteSpace(sparkline))
        {
            description += $"\n\n**Waveform Snapshot:**\n```{sparkline}```";
        }

        var embed = new
        {
            title = $"🚨 Telemetry Anomaly Detected: {anomaly.ChannelName}",
            description,
            color,
            fields = new object[]
            {
                new { name = "Z-Score", value = $"{anomaly.ZScore:F2}σ", inline = true },
                new { name = "Current Value", value = $"{anomaly.CurrentValue:F2}", inline = true },
                new { name = "Est. Breach Time", value = $"{(anomaly.EstimatedTimeToBreachSec > 0 ? $"{anomaly.EstimatedTimeToBreachSec:F1}s" : "N/A")}", inline = true }
            },
            footer = new { text = "TelemetryDashboard Anomaly Monitor" },
            timestamp = DateTime.UtcNow.ToString("o")
        };

        return JsonSerializer.Serialize(new { embeds = new[] { embed } }, new JsonSerializerOptions { WriteIndented = false });
    }

    public string FormatTelegramPayload(AnomalyResult anomaly, string aiDiagnosis)
    {
        string text = $"🚨 *[ANOMALY ALERT]* `{anomaly.ChannelName}`\n" +
                      $"• *Z-Score:* {anomaly.ZScore:F2}σ\n" +
                      $"• *Current Value:* {anomaly.CurrentValue:F2}\n" +
                      $"• *Mean / StdDev:* {anomaly.Mean:F2} / {anomaly.StdDev:F2}\n" +
                      $"• *Est. Breach:* {(anomaly.EstimatedTimeToBreachSec > 0 ? $"{anomaly.EstimatedTimeToBreachSec:F1}s" : "N/A")}";

        if (!string.IsNullOrWhiteSpace(aiDiagnosis))
        {
            text += $"\n\n🤖 *AI Diagnosis:*\n{aiDiagnosis}";
        }

        var payload = new
        {
            chat_id = Config.TelegramChatId,
            text,
            parse_mode = "Markdown"
        };

        return JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = false });
    }

    public string FormatGenericWebhookPayload(AnomalyResult anomaly, string aiDiagnosis, string sparkline, string svgWaveform, WaveformStats stats)
    {
        var payload = new
        {
            alertId = Guid.NewGuid().ToString(),
            timestamp = DateTime.UtcNow.ToString("o"),
            severity = anomaly.ZScore >= 3.5 ? "CRITICAL" : "WARNING",
            channelName = anomaly.ChannelName,
            zScore = anomaly.ZScore,
            currentValue = anomaly.CurrentValue,
            mean = anomaly.Mean,
            stdDev = anomaly.StdDev,
            estimatedTimeToBreachSec = anomaly.EstimatedTimeToBreachSec,
            aiDiagnosis = string.IsNullOrWhiteSpace(aiDiagnosis) ? "Anomaly detected" : aiDiagnosis,
            sparkline,
            svgWaveform,
            stats = new
            {
                min = stats.Min,
                max = stats.Max,
                mean = stats.Mean,
                peakToPeak = stats.PeakToPeak,
                stdDev = stats.StdDev,
                count = stats.Count
            }
        };

        return JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = false });
    }

    public async Task<bool> DispatchAlertAsync(
        AnomalyResult anomaly,
        string aiDiagnosisText = "",
        IEnumerable<double>? recentSamples = null,
        CancellationToken cancellationToken = default)
    {
        if (anomaly == null) return false;

        DateTime now = _utcNow();
        if (ShouldThrottle(anomaly.ChannelName, anomaly.ZScore, now))
        {
            return false;
        }

        _channelThrottles[anomaly.ChannelName] = (now, anomaly.ZScore);

        string sparkline = WaveformSnapshotGenerator.GenerateAsciiSparkline(recentSamples);
        string svg = WaveformSnapshotGenerator.GenerateSvgWaveform(recentSamples);
        var stats = WaveformSnapshotGenerator.ComputeStats(recentSamples);

        var tasks = new List<Task>();

        // 1. Slack
        if (Config.EnableSlack && !string.IsNullOrWhiteSpace(Config.SlackWebhookUrl))
        {
            string json = FormatSlackPayload(anomaly, aiDiagnosisText, sparkline);
            tasks.Add(PostPayloadAsync(Config.SlackWebhookUrl, json, cancellationToken));
        }

        // 2. Discord
        if (Config.EnableDiscord && !string.IsNullOrWhiteSpace(Config.DiscordWebhookUrl))
        {
            string json = FormatDiscordPayload(anomaly, aiDiagnosisText, sparkline);
            tasks.Add(PostPayloadAsync(Config.DiscordWebhookUrl, json, cancellationToken));
        }

        // 3. Telegram
        if (Config.EnableTelegram && !string.IsNullOrWhiteSpace(Config.TelegramBotToken) && !string.IsNullOrWhiteSpace(Config.TelegramChatId))
        {
            string url = $"https://api.telegram.org/bot{Config.TelegramBotToken}/sendMessage";
            string json = FormatTelegramPayload(anomaly, aiDiagnosisText);
            tasks.Add(PostPayloadAsync(url, json, cancellationToken));
        }

        // 4. Generic Webhook
        if (Config.EnableGenericWebhook && !string.IsNullOrWhiteSpace(Config.GenericWebhookUrl))
        {
            string json = FormatGenericWebhookPayload(anomaly, aiDiagnosisText, sparkline, svg, stats);
            tasks.Add(PostPayloadAsync(Config.GenericWebhookUrl, json, cancellationToken));
        }

        if (tasks.Count > 0)
        {
            await Task.WhenAll(tasks);
        }

        return true;
    }

    private async Task PostPayloadAsync(string url, string json, CancellationToken cancellationToken)
    {
        try
        {
            using var content = new StringContent(json, Encoding.UTF8, "application/json");
            await _httpClient.PostAsync(url, content, cancellationToken);
        }
        catch
        {
            // Suppress transport network errors to maintain service resilience
        }
    }
}
